language: java

sudo: required
dist: bionic

services:
  - docker

branches:
  only:
    - master

install:
  - sudo apt update

script:
  - make all

deploy:
  provider: releases
  file: resume.pdf
  skip_cleanup: true
  api_key: '$GITHUB_API_KEY'
  overwrite: true
  on:
    tags: true
    branch: master
