language: java

sudo: required
dist: bionic

services:
  - docker

branches:
  only:
    - master

install:
  - sudo apt update

script:
  - make all
  - mkdir build

deploy:
  provider: releases
  file: resume.pdf
  skip_cleanup: true
  api_key: '$GITHUB_API_KEY'
  on:
    tags: true
    branch: master
