language: java

sudo: required
dist: bionic

services:
  - docker

branches:
  only:
    - master

install:
  - sudo apt update

script:
  - make all

after_success:
  - make release

deploy:
  provider: releases
  file:
    - resume.pdf
  skip_cleanup: true
  api_key:
    secure: ${GITHUB_API_KEY}
  overwrite: true
  file_glob: true
  on:
    branch: master
    tags: true
